# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Azure Vision Machine Learning Platform Team (3cfa45ba-9ce3-42fb-9e1a-47374e9dea5b)'
    KeyVaultName: 'acv-dp-wu2-t-001-kv'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: DotNetCoreCLI@2
  displayName: 'build my app'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'run my app'
  env:
    cvatPassword: $(cvatPassword)
  inputs:
    command: 'run'
    projects: '**/*.csproj'